# Generated by Django 3.2.6 on 2021-09-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('cropType', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('cropParameters', models.CharField(default='None', max_length=256)),
            ],
        ),
    ]
