# Generated by Django 3.2.5 on 2021-08-10 03:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModels',
            new_name='UserModel',
        ),
    ]
