# Generated by Django 3.2.6 on 2021-08-29 03:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paddocks', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yields', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YieldModel',
            new_name='Yield',
        ),
    ]
