# Generated by Django 3.2.6 on 2021-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yields', '0002_rename_yieldmodel_yield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yield',
            name='harvest_t',
            field=models.FloatField(),
        ),
    ]
